import Head from "next/head";
import { Inter } from "next/font/google";
import Home from "./Home/Home.component";

const inter = Inter({ subsets: ["latin"] });

export default function Homes() {
  return (
    <>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`} style={{ overflowX: "hidden" }}>
        <Home />
      </main>
    </>
  );
}
